# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic_message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64ynamic_message.proto\x12\x07\x64ynamic\"`\n\x04\x44\x61ta\x12)\n\x06values\x18\x01 \x03(\x0b\x32\x19.dynamic.Data.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x18\n\x08\x46unction\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xa4\x01\n\x0e\x44ynamicService\x12+\n\x08SendData\x12\r.dynamic.Data\x1a\x0e.dynamic.Empty\"\x00\x12\x30\n\x0bReceiveData\x12\x0e.dynamic.Empty\x1a\r.dynamic.Data\"\x00\x30\x01\x12\x33\n\x0c\x43\x61llFunction\x12\x11.dynamic.Function\x1a\x0e.dynamic.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dynamic_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA_VALUESENTRY']._loaded_options = None
  _globals['_DATA_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_DATA']._serialized_start=34
  _globals['_DATA']._serialized_end=130
  _globals['_DATA_VALUESENTRY']._serialized_start=85
  _globals['_DATA_VALUESENTRY']._serialized_end=130
  _globals['_FUNCTION']._serialized_start=132
  _globals['_FUNCTION']._serialized_end=156
  _globals['_EMPTY']._serialized_start=158
  _globals['_EMPTY']._serialized_end=165
  _globals['_DYNAMICSERVICE']._serialized_start=168
  _globals['_DYNAMICSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
